spring:
  application:
    name: sfdcevent

# application.yml
salesforce:
  login-url: https://axaid-ccc--sbrlsdmtm.sandbox.my.salesforce.com
  client-id: <test>
  client-secret: <test>
  grant_type: client_credentials